Pokebook.web/Controllers/PokedexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pokebook.core.Data;
using Pokebook.core.Models;
using Pokebook.core.Models.DTO;
using Pokebook.web.Helpers;
using Pokebook.web.Models;

namespace Pokebook.web.Controllers
{
    public class PokedexController : Controller
    {
        public PokedexController(PokebookContext context)
        {
            Constants constants = new Constants();
            baseuri = $"{constants.ApiServerSideAddress}/api";
            baseuriClient = $"{constants.ApiClientSideAddress}/api";
            pokemonContext = context;
        }

        readonly string baseuri;
        readonly string baseuriClient;
        private PokebookContext pokemonContext;

        public Guid? CheckSession()
        {
            string id = HttpContext.Session.GetString("UserId");
            if (id != null) return Guid.Parse(id);
            else return null;
        }

        public async Task<UserSimpleDTO> GetUserWithId(Guid userId)
        {
            string uri = $"{baseuri}/users/{userId}";
            return await WebApiHelper.GetApiResult<UserSimpleDTO>(uri);
        }

        public async Task<IActionResult> Index()
        {
            Guid userId;
            Guid? tempUserId = CheckSession();
            if (tempUserId == null) return new RedirectToActionResult("Login", "Account", null);
            else userId = (Guid)tempUserId;

            UserSimpleDTO user = await GetUserWithId(userId);

            var vm = new PokedexIndexVM
            {
                Username = user.UserName,
                BaseUri = baseuriClient
            };

            string uri = $"{baseuri}/Pokemons/GetAll";
            List<Pokemon> allPokemon = await WebApiHelper.GetApiResult<List<Pokemon>>(uri);
            vm.AllPokemonWithTypeInfo = allPokemon;

            uri = $"{baseuri}/PokemonCatches/GetMyPokemon/{user.Id}";
            List<PokemonCatch> allCaughtPokemon = await WebApiHelper.GetApiResult<List<PokemonCatch>>(uri);
            vm.AllCaughtPokemon = allCaughtPokemon;

            return View(vm);
        }

        public async Task<IActionResult> Pokemon(short ndex)
        {
            Guid userId;
            Guid? tempUserId = CheckSession();
            if (tempUserId == null) return new RedirectToActionResult("Login", "Account", null);
            else userId = (Guid)tempUserId;

            UserSimpleDTO user = await GetUserWithId(userId);

            string uri = $"{baseuri}/Pokemons/GetByNdex/{ndex}";
            Pokemon thisPoke = await WebApiHelper.GetApiResult<Pokemon>(uri);

            uri = $"{baseuri}/PokemonUsers/GetById/{thisPoke.Id}/{user.Id}";
            PokemonUser pokemonUser = await WebApiHelper.GetApiResult<PokemonUser>(uri);
            short numberOfCatches = 0;
            if (pokemonUser != null) numberOfCatches = pokemonUser.Catches;

            StringBuilder sb = new StringBuilder();
            var colors = new string[2];
            colors[0] = thisPoke.PokemonTypes.FirstOrDefault().Type.Colour;
            colors[1] = (thisPoke.PokemonTypes.Count < 2) ? colors[0] : thisPoke.PokemonTypes.ElementAtOrDefault(1).Type.Colour;
            foreach (var t in thisPoke.PokemonTypes) sb.Append($"{t.Type.Name} ");

            PokedexPokemonVM vm = new PokedexPokemonVM
            {
                SelectedPokemon = thisPoke,
                Catches = numberOfCatches,
                Colors = colors,
                Sb = sb,
                BaseUri = baseuriClient
            };

            return View(vm);
        }

        /*public IActionResult Error(int? statusCode) //refactor to simplicity/more use
        {
            string userName = HttpContext.Session.GetString("Username");
            if (userName == null) return new RedirectToActionResult("Login", "Account", null);

            if (statusCode.HasValue)
            {
                int? vn = 200;
                switch (statusCode)
                {
                    case (int?)HttpStatusCode.NotFound:
                        vn = statusCode;
                        break;
                    default:
                        break;
                }
                return View($"Page{vn.ToString()}");
            }
            return View();
        }*/

        /*private async Task<IEnumerable<Pokemon>> getAllCaught(string username)
        {
            var numberOfPokemon = await pokemonContext.Set<PokemonUser>()
                    .Include(pu => pu.Pokemon).ThenInclude(p => p.PokemonUsers)
                    .Include(pu => pu.User).ThenInclude(u => u.PokemonUsers)
                    .Where(u => u.User.Username == username)
                    .CountAsync();

            List<Pokemon> myPokemonList = new List<Pokemon>();
            if (numberOfPokemon != 0)
            {
                var allPoke = await pokemonContext.Set<PokemonUser>()//all pokemonuser objects per current user
                    .Include(pu => pu.Pokemon).ThenInclude(p => p.PokemonUsers)
                    .Include(pu => pu.User).ThenInclude(u => u.PokemonUsers)
                    .Where(u => u.User.Username == username).ToListAsync();

                foreach (var el in allPoke) myPokemonList.Add(el.Pokemon);
            }
            else myPokemonList = new List<Pokemon>();
            return myPokemonList;
        }*/
    }
}

Pokebook.web/Views/Shared/Partial/PokemonCatchesListViewPartial.cshtml
@model PokedexIndexVM

<div class="pokelist">
    <aside id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Sort pokemon</h4>
                </div>
                <div class="modal-body">
                        <div v-for="sortTerm in sortTerms" id="sortTerms">
                            <div v-on:click="getSelectedSortTerm">
                                <img v-bind:src="'/images/' + sortTerm + '.png'" width="20" v-bind:data-sortTerm="sortTerm"/>
                                <span v-bind:data-sortTerm="sortTerm">{{sortTerm}}</span>
                            </div>
                        </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </aside>
    @{
        <div class="pokecell" v-for="pokemon in listPokemonCatchesToEdit">
            <p>cp {{pokemon.cp}}</p>
            <a :href="'/Pokemon/' + pokemon.pokemon.nDex">
                <img v-bind:src="'@(Model.BaseUri)/pokemons/PokemonPicture/' + pokemon.pokemon.imgUrl + '/' + pokemon.folderType"
                     v-bind:alt="'pokemon.pokemon.name'" onerror="this.src='/images/default.png'" />
            </a>
            <p>{{pokemon.pokemon.name}}</p>
        </div>
    }
</div>


@{
    /*<div class="pokelist">
    @{
        foreach (var pokemon in Model.AllCaughtPokemon.OrderBy(m => m.Pokemon.NDex))
        {
            var colors = new string[2];
            colors[0] = pokemon.Pokemon.PokemonTypes.FirstOrDefault().Type.Colour;
            colors[1] = (pokemon.Pokemon.PokemonTypes.Count < 2) ? colors[0] : pokemon.Pokemon.PokemonTypes.ElementAtOrDefault(1).Type.Colour;

            <div class="pokecell" style="background: linear-gradient(90deg, @colors[0] 50%, @colors[1] 50%);">
                <a title="@pokemon.Pokemon.Name" asp-controller="Pokedex" asp-action="Pokemon" asp-route-ndex="@pokemon.Pokemon.NDex">
                    <img src="@(Model.BaseUri)/pokemons/PokemonPicture/@(pokemon.Pokemon.ImgUrl)/@(pokemon.FolderType)"
                         alt="@(pokemon.Pokemon.Name)" title="@(pokemon.Pokemon.Name)" />
                </a>
            </div>
        }
    }
</div>*/
}

Pokebook.web/Views/Shared/Partial/PokemonListViewPartial.cshtml
@model PokedexIndexVM

<div class="pokelist">
    @{
        foreach (var pokemon in Model.AllPokemonWithTypeInfo.OrderBy(p => p.NDex).Distinct())
        {
            var colors = new string[2];
            colors[0] = pokemon.PokemonTypes.FirstOrDefault().Type.Colour;
            colors[1] = (pokemon.PokemonTypes.Count < 2) ? colors[0] : pokemon.PokemonTypes.ElementAtOrDefault(1).Type.Colour;
            <div class="pokecell" style="background: linear-gradient(90deg, @colors[0] 50%, @colors[1] 50%);">
                <a title="@pokemon.Name" asp-controller="Pokedex" asp-action="Pokemon" asp-route-ndex="@pokemon.NDex">
                    <img src="@(Model.BaseUri)/pokemons/PokemonPicture/@(pokemon.ImgUrl)/normal"
                         alt="@(pokemon.Name)" title="@(pokemon.Name)" />
                </a>
            </div>
        }
    }
</div>

Pokebook.web/Views/Shared/Partial/PokemonToCatchPartial.cshtml
@model ExploreCatchVm
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="row generatePokemon">
    <div class="col-md-12">
        <img src="@(Model.BaseUri)/pokemons/PokemonPicture/@(Model.AppearedPokemon.Pokemon.ImgUrl)/@(Model.FolderType)" class="pokemon"
             alt="@(Model.AppearedPokemon.Pokemon.Name)" title="It's @(Model.AppearedPokemon.Pokemon.Name)" /><br />

        <button type="submit" class="pokeball" title="Go Pokeball!">
            <img src="~/images/Backgrounds/Pokeball.png" alt="Pokeball" />
        </button>
    </div>
    <!--<div class="col-md-12"> //geeft nog problemen als er code moet uitgevoerd worden -> 
                                  Er kunnen meer properties meegegeven worden aan de Partial. Of we maken geen gebruik van een partial.
        <ul>
            <li></li>
        </ul>
    </div>-->
</div>

Pokebook.web/Views/Shared/Partial/UserListPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<div class="form-group" id="userSearch">
    <input list="userList" id="userListValue" placeholder="Search" v-on:change='getSelectedUser($event)'>
    <datalist id="userList">
        <option v-for="user in users" v-bind:value="user">{{user}}</option>
    </datalist>
</div>