Pokebook.web/Components/ChatListViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Pokebook.core.Models;
using Pokebook.web.Helpers;
using Pokebook.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pokebook.web.Components
{
    public class ChatListViewComponent : ViewComponent
    {
        public ChatListViewComponent()
        {
            Constants constants = new Constants();
            baseuri = $"{constants.ApiServerSideAddress}/api";
        }

        string baseuri;

        public async Task<IViewComponentResult> InvokeAsync()
        {
            Guid userId = Guid.Parse(HttpContext.Session.GetString("UserId"));
            string uri = $"{baseuri}/chats/userId/{userId}";
            List<Chat> chatListForUser = await WebApiHelper.GetApiResult<List<Chat>>(uri);

            uri = $"{baseuri}/users/{userId}";
            User currentUser = await WebApiHelper.GetApiResult<User>(uri);

            AllChatsForUserVM vm = new AllChatsForUserVM
            {
                ListChats = chatListForUser,
                Username = currentUser.UserName
            };
            return View(vm);
        }
    }
}

Pokebook.web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Pokebook.core.Models;
using Pokebook.core.Models.DTO;
using Pokebook.web.Helpers;
using Pokebook.web.Models;

namespace Pokebook.web.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {
            Constants constants = new Constants();
            baseuri = $"{constants.ApiServerSideAddress}/api";
        }

        readonly string baseuri;

        public Guid? CheckSession()
        {
            string id = HttpContext.Session.GetString("UserId");
            if (id != null) return Guid.Parse(id);
            else return null;
        }

        public IActionResult Index()
        {
            Guid? userId = CheckSession();
            if (userId == null) return new RedirectToActionResult("Login", "Account", null);
            return View();
        }

        public IActionResult About()
        {
            Guid? userId = CheckSession();
            if (userId == null) return new RedirectToActionResult("Login", "Account", null);
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            Guid? userId = CheckSession();
            if (userId == null) return new RedirectToActionResult("Login", "Account", null);
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            Guid? userId = CheckSession();
            if (userId == null) return new RedirectToActionResult("Login", "Account", null);
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            Guid? userId = CheckSession();
            if (userId == null) return new RedirectToActionResult("Login", "Account", null);
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pokebook.web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Pokebook.web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Pokebook.web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Constants constants = new Constants();
}

<div class="row friendRequests">
    <aside id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Friend requests {{numberOfRequests}}</h4>
                </div>
                <div class="modal-body">
                    <h3>{{ loadingMessage }}</h3>
                    <div class="row" v-for="friend in friendRequests">
                        <div class="col-md-4">
                            <img v-bind:src="'@(constants.ApiClientSideAddress)/api/users/ProfilePicture/' + friend.profilePicture"
                                 v-bind:alt="'friend.ProfilePicture'" onerror="this.src='/images/default.png'" id="RequestProfilePicture" />
                        </div>
                        <div class="col-md-4">
                            <a :href="`/Profile/UserProfile/${friend.userName}`">{{friend.userName}}</a>
                            <p>{{ friend.firstName }} {{friend.lastName}}</p>
                        </div>
                        <div class="col-md-4">
                            <button v-on:click="approveFriendRequest(friend)" class="btn btn-primary">Approve</button>
                            <button v-on:click="ignoreFriendRequest(friend)" class="btn btn-primary">Ignore</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </aside>
    <aside class="col-md-3 sideBar">
        <div class="nav-icons">
            <a asp-controller="Profile" asp-action="index">
                <img v-bind:src="'@(constants.ApiClientSideAddress)/api/users/ProfilePicture/' + profilePicture"
                    v-bind:alt="profilePicture" onerror="this.src='/images/default.png'" id="profilePicture" />
                <!--<img v-bind:src="'@(constants.ApiClientSideAddress)/api/users/ProfilePicture/' + profilePicture"
         v-bind:alt="profilePicture" id="profilePicture" />-->
            </a>
            <img src="~/images/friendRequests.png" alt="Friend Requests" title="Friend Requests"
                 id="friendRequests" data-toggle="modal" data-target="#myModal" />
        </div>
        <vc:chat-list></vc:chat-list>
    </aside>
    <main class="col-md-9" id="pokeTimeLine">
        <partial name="Partial/UserListPartial"/>
        <h2>Pokebook timeline will be displayed here in version 2.0</h2>
        <div id="posts">
            @*Hier komen alle time line posts via Vue.js*@
            <h3>{{ loadingMessage }}</h3>
            @{
                List<string> testPostList = new List<string> { "Post 1", "Post 2", "Post 3" };
                foreach (var post in testPostList)
                {
                    <div>@post</div>
                }
            }
        </div>
    </main>
</div>

@section scripts{
    <script src="~/js/vue.js"></script>
    <script src="~/js/timeLine.js"></script>
    <script src="~/js/vueHomePage.js"></script>
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/chatNotification.js"></script>
}